using System;
using NUnit.Framework;
using System.Collections.Generic;

[TestFixture]
class Class1Test
{
    [Test]
    public void newMethod()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod2()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMetho3()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod4()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod5()
    {
        Assert.Fail("autogenerated");
    }
}