using System;
using NUnit.Framework;
using System.Collections.Generic;

[TestFixture]
class Class2Test
{
    [Test]
    public void newMethod()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod1()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod2()
    {
        Assert.Fail("autogenerated");
    }

    [Test]
    public void newMethod3()
    {
        Assert.Fail("autogenerated");
    }
}